blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ DH electronics Support
    url: https://github.com/dh-electronics
    about: For questions, issues, or contributions, please see the contact information on the DH electronics GitHub organization profile.
